name: Generate MDs (Rust)

on:
  schedule:
    - cron: "30 0-2,8-23/2 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Checkout base files
      uses: actions/checkout@v7
      with:
        persist-credentials: false
        repository: caiocampos/readme-base
        path: base
        sparse-checkout: |
          files
          md.conf.json
    - name: Checkout repos-md.json file
      uses: actions/checkout@v7
      with:
        persist-credentials: false
        repository: caiocampos/caiocampos.github.io
        path: repos
        sparse-checkout: |
          repos-md.json
    - name: Organize folders
      run: |
           mkdir -p ./out
           cp -r ./base/* ./
           rm -f ./files/repos-md.json
           cp -f ./repos/repos-md.json ./files/repos-md.json
           rm -rf ./base
           rm -rf ./repos
    - name: Download Batch Binary
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
           gh release download -R caiocampos/md-fuse -p "md_fuse"
           chmod +x md_fuse
    - name: Run
      run: |
           export VERSION=$(date +'%Y%m%d%H%M%S')
           ./md_fuse
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        folder: out
        clean: false
