name: Generate MDs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout md-fuse
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        repository: caiocampos/md-fuse
    - name: Checkout base files
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        ref: base
        path: out
    - name: Organize folders
      run: |
           cp -r ./out/* ./
           rm -rf ./out/files
           rm -f ./out/md.conf.json
    - name: Download Charts
      run: |
           curl -o ./out/cr-skills-chart-widget.svg \
           "https://cr-skills-chart-widget.azurewebsites.net/api/api?username=caiocampos&sort-by-score=true&skills=JavaScript,TypeScript,Rust,Go,Java,Python,C%2b%2b,C,C%23&branding=false&bg=%23fffc"
           curl -o ./out/top-languages.svg \
           "https://github-readme-stats.vercel.app/api/top-langs?username=caiocampos&hide_title=true&layout=default&hide=c,html,css,makefile&langs_count=8&exclude_repo=Random-Stuff,Java-Random-Stuff,C-Random-Stuff"
           curl -o ./out/top-languages-dark.svg \
           "https://github-readme-stats.vercel.app/api/top-langs?username=caiocampos&hide_title=true&layout=default&hide=c,html,css,makefile&langs_count=8&exclude_repo=Random-Stuff,Java-Random-Stuff,C-Random-Stuff&theme=tokyonight"
    - name: Run
      run: cargo run
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        folder: out
        clean: false
