name: Generate MDs (Python)

on:
  #schedule:
  #  - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v8.3.1
      with:
        enable-cache: true
        cache-prefix: ${{ matrix.python-version }}
    - name: Pin python-version ${{ matrix.python-version }}
      run: uv python pin ${{ matrix.python-version }}
    - name: Checkout md-fuse-py
      uses: actions/checkout@v7
      with:
        persist-credentials: false
        repository: caiocampos/md-fuse-py
    - name: Checkout base files
      uses: actions/checkout@v7
      with:
        persist-credentials: false
        repository: caiocampos/readme-base
        path: base
        sparse-checkout: |
          files
          md.conf.json
    - name: Checkout repos-md.json file
      uses: actions/checkout@v7
      with:
        persist-credentials: false
        repository: caiocampos/caiocampos.github.io
        ref: master
        path: repos
        sparse-checkout: |
          repos-md.json
    - name: Organize folders
      run: |
           mkdir -p ./out
           cp -r ./base/* ./
           cp -f ./repos/repos-md.json ./files/json/repos-md.json
           rm -rf ./base
           rm -rf ./repos
    - name: Sync dependencies
      run: uv sync
    - name: Run
      run: |
           export VERSION=$(date +'%Y%m%d%H%M%S')
           uv run fuse
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        folder: out
        clean: false
