name: Generate MDs (Rust)

on:
  #schedule:
    #- cron: "0 0 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      SKILLS_CHART: "https://cr-skills-chart-widget.azurewebsites.net/api/api?username=caiocampos&sort-by-score=true&skills=JavaScript,TypeScript,Rust,Go,Java,Python,C%2b%2b,C,C%23&branding=false&bg=%23fffc&padding=15"
      README_STATS: "https://github-readme-stats.vercel.app/api/top-langs?username=caiocampos&hide_title=true&hide=html,css&langs_count=8&exclude_repo=Java-Random-Stuff,C-Random-Stuff,GLAE,Opcao-MpC"
      COLON: ":"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout md-fuse
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        repository: caiocampos/md-fuse
    - name: Checkout base files
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        ref: base
        path: out
    - name: Organize folders
      run: |
           cp -r ./out/* ./
           rm -rf ./out/files
           rm -f ./out/md.conf.json
    - name: Add version watermark
      run: echo -e "\n[comment]$COLON # (version$COLON $(date +'%Y%m%d%H%M%S'))" >> ./files/trailer.md
    - name: Download Charts
      run: |
           curl -o ./out/cr-skills-chart-widget.svg "${{env.SKILLS_CHART}}"
           curl -o ./out/top-languages.svg "${{env.README_STATS}}"
           curl -o ./out/top-languages-dark.svg "${{env.README_STATS}}&theme=tokyonight"
    - name: Run
      run: cargo run
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        folder: out
        clean: false
