name: Generate files

on:
  schedule:
    - cron: "0 16,18,21 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update files
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v0.0.18
        id: snake-gif
        with:
          github_user_name: caiocampos
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          folder: dist
