name: Generate files

on:
  schedule:
    - cron: "0 16,18,21 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update files
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v0.0.18
        id: snake-gif
        with:
          github_user_name: caiocampos
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
