name: Metrics
on:
  schedule:
    - cron: "0 18,21 * * *"
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: metrics
          user: caiocampos
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 10
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: stack
          config_padding: 0, 8 + 25%
