name: Run Tests

on:
  schedule:
    - cron: "0/6 0-2,8-23 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to test servers
    runs-on: ubuntu-latest
    steps:
      - name: Create script
        run: curl -O https://raw.githubusercontent.com/caiocampos/modular-server/refs/heads/master/scripts/test-servers.sh
      - name: Run script
        run: bash test-servers.sh
