name: Run Tests

on:
  #schedule:
    #- cron: "1/10 0,8-23 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to test servers
    runs-on: ubuntu-latest
    steps:
      - name: Create script
        run: curl -o test-servers.sh https://github.com/caiocampos/modular-server/raw/refs/heads/master/scripts/test-servers.sh
        shell: bash
      - name: Run script
        run: bash test-servers.sh
