name: Snake

on:
  schedule:
    - cron: "0 16,18,21 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update files
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-svg
        with:
          github_user_name: caiocampos
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: snake
          folder: dist
