name: Snake

on:
  schedule:
    - cron: "0 16,18,21 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update files
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-svg
        with:
          github_user_name: caiocampos
          svg_out_path: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: snake
          publish_dir: ./dist
