name: Generate top languages chart

on:
  schedule:
    - cron: "5 1,22 * * *"
  workflow_dispatch:

jobs:
  build:
    env:
      README_STATS: "username=caiocampos&hide_title=true&hide=html,css,scss,makefile&langs_count=10&exclude_repo=JVM-Random-Stuff,Zig-C-Random-Stuff,GLAE"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v2
        with:
          card: top-langs
          options:  ${{ env.README_STATS }}
          path: out/top-languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate stats card (dark)
        uses: readme-tools/github-readme-stats-action@v2
        with:
          card: top-langs
          options:   ${{ env.README_STATS }}&theme=tokyonight
          path: out/top-languages-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          folder: out
          clean: false
