name: Generate files

on:
  schedule:
    - cron: "0/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update files
    runs-on: ubuntu-latest
    steps:
      - name: shrtr HTTP Request
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: 'https://shrtr.caiocampos.repl.co/@/count'
          method: 'GET'
