name: Wake-up servers

on:
  schedule:
    - cron: "1/10 0,8-23 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to wake-up servers
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Requests
        run: >
             sleep_random () {
                 SLEEP_TIME=$((10 + RANDOM % 21));
                 echo "sleeping ${SLEEP_TIME}s";
                 sleep $SLEEP_TIME;
             }
             for i in `seq 1 $((1 + RANDOM % 4))``; do (
                 echo "response shrtr -> $(curl -s https://shrtr.onrender.com/@/count)";
                 sleep_random;
                 echo "response blog-posts -> $(curl -s https://blog-posts-enji.onrender.com/authors/count)";
                 sleep_random;
                 echo "response asteroid-score -> $(curl -s https://asteroid-score.onrender.com/score/count)";
                 sleep_random;
                 );
             done
        shell: bash
